import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../../../globals.css'
import { ClerkProvider, currentUser } from "@clerk/nextjs"
import Topbar from '@/components/shared/Topbar'
import BottomBar from '@/components/shared/Bottombar'
import LeftSidebar from '@/components/shared/LeftSidebar'
import RightSidebar from '@/components/shared/RightSidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const user = await currentUser();

  return (
    <main className='flex flex-row flex-1'>
      <section className='main-container'>
        <div className='w-full max-w-4xl'>
          {children}
        </div>
      </section>

      <RightSidebar />
    </main>
  )
}
